language: cpp

sudo: required
dist: xenial

branches:
  only:
    - master

matrix:
  include:
  - env: BUILD_TYPE=Release
  - env: BUILD_TYPE=Debug
  - os: osx
    compiler: clang
    before_install:
    - brew update
    - brew install
        sdl2
        sdl2_image
        sdl2_mixer
        sdl2_ttf
    env: BUILD_TYPE=Release

addons:
  apt:
    packages:
      - libsdl2-dev
      - libsdl2-image-dev
      - libsdl2-mixer-dev
      - libsdl2-ttf-dev

before_install:
  - if [[ $TRAVIS_OS_NAME == linux && $BUILD_TYPE == Release ]]; then
      wget https://github.com/mmatyas/mmatyas.github.io/releases/download/arm-libs/appstream-085-ubuntu1404.tgz &&
      sudo tar xzf appstream-085-ubuntu1404.tgz -C /;
    fi

before_script:
  - $CXX --version
  - cmake --version
  - sdl2-config --version

script:
  - mkdir build && cd build
  - cmake ..
      -DCMAKE_INSTALL_PREFIX=/usr
      -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
      -DENABLE_MP3=OFF
  - make VERBOSE=1
  - if [[ $BUILD_TYPE == Debug ]]; then
      ./tests/openblok_test;
    fi
  - if [[ $TRAVIS_OS_NAME == linux && $BUILD_TYPE == Release ]]; then
      bash -e ../etc/appimage/travis.sh &&
      chmod +x ~/out/OpenBlok*.AppImage &&
      wget -c https://github.com/mmatyas/uploadtool/raw/master/upload.sh &&
      bash ./upload.sh ~/out/OpenBlok*.AppImage;
    fi
